f_num = int(input("Give me the first number: "))
s_num = int(input("Give me the second number: "))
print("Thank you!")
print(f_num, "+", s_num, "=", f_num + s_num)
print(f_num, "-", s_num, "=", f_num - s_num)
print(f_num, "/", s_num, "=", int(f_num / s_num))
print(f_num, "*", s_num, "=", f_num * s_num)